services:
  postgres:
    image: postgres:15-alpine
    container_name: tp_spark_postgres
    environment:
      POSTGRES_DB: db_gold
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
